# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Editor.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 657)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setWindowTitle("FoE Save Editor")
        MainWindow.setStyleSheet("")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Triangular)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(800, 600))
        self.tabWidget.setMaximumSize(QtCore.QSize(1920, 1080))
        self.tabWidget.setToolTip("")
        self.tabWidget.setStatusTip("")
        self.tabWidget.setWhatsThis("")
        self.tabWidget.setAccessibleName("")
        self.tabWidget.setAccessibleDescription("")
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setObjectName("tabWidget")
        self.player_tab = QtWidgets.QWidget()
        self.player_tab.setObjectName("player_tab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.player_tab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_20 = QtWidgets.QLabel(self.player_tab)
        self.label_20.setText("General")
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_5.addWidget(self.label_20)
        self.name_layout = QtWidgets.QFormLayout()
        self.name_layout.setObjectName("name_layout")
        self.characterName = QtWidgets.QLineEdit(self.player_tab)
        self.characterName.setObjectName("characterName")
        self.name_layout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.characterName)
        self.label_51 = QtWidgets.QLabel(self.player_tab)
        self.label_51.setText("Name")
        self.label_51.setObjectName("label_51")
        self.name_layout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_51)
        self.verticalLayout_5.addLayout(self.name_layout)
        self.frame_4 = QtWidgets.QFrame(self.player_tab)
        self.frame_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_5.addWidget(self.frame_4)
        self.label_7 = QtWidgets.QLabel(self.player_tab)
        self.label_7.setText("Stats")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_5.addWidget(self.label_7)
        self.tabWidget_2 = QtWidgets.QTabWidget(self.player_tab)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.formLayout_6 = QtWidgets.QFormLayout()
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_34 = QtWidgets.QLabel(self.tab_3)
        self.label_34.setText("DexG")
        self.label_34.setObjectName("label_34")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_34)
        self.dexG = QtWidgets.QDoubleSpinBox(self.tab_3)
        self.dexG.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.dexG.setPrefix("")
        self.dexG.setSuffix("")
        self.dexG.setDecimals(1)
        self.dexG.setMinimum(1.0)
        self.dexG.setSingleStep(0.1)
        self.dexG.setObjectName("dexG")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.dexG)
        self.label_35 = QtWidgets.QLabel(self.tab_3)
        self.label_35.setText("IntG")
        self.label_35.setObjectName("label_35")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_35)
        self.inteG = QtWidgets.QDoubleSpinBox(self.tab_3)
        self.inteG.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.inteG.setPrefix("")
        self.inteG.setSuffix("")
        self.inteG.setDecimals(1)
        self.inteG.setMinimum(1.0)
        self.inteG.setSingleStep(0.1)
        self.inteG.setObjectName("inteG")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.inteG)
        self.label_36 = QtWidgets.QLabel(self.tab_3)
        self.label_36.setText("LibG")
        self.label_36.setObjectName("label_36")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_36)
        self.libG = QtWidgets.QDoubleSpinBox(self.tab_3)
        self.libG.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.libG.setPrefix("")
        self.libG.setSuffix("")
        self.libG.setDecimals(1)
        self.libG.setMinimum(1.0)
        self.libG.setSingleStep(0.1)
        self.libG.setObjectName("libG")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.libG)
        self.label_38 = QtWidgets.QLabel(self.tab_3)
        self.label_38.setText("StaG")
        self.label_38.setObjectName("label_38")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_38)
        self.staG = QtWidgets.QDoubleSpinBox(self.tab_3)
        self.staG.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.staG.setPrefix("")
        self.staG.setSuffix("")
        self.staG.setDecimals(1)
        self.staG.setMinimum(1.0)
        self.staG.setSingleStep(0.1)
        self.staG.setObjectName("staG")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.staG)
        self.label_39 = QtWidgets.QLabel(self.tab_3)
        self.label_39.setText("StrG")
        self.label_39.setObjectName("label_39")
        self.formLayout_6.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_39)
        self.strG = QtWidgets.QDoubleSpinBox(self.tab_3)
        self.strG.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.strG.setPrefix("")
        self.strG.setSuffix("")
        self.strG.setDecimals(1)
        self.strG.setMinimum(1.0)
        self.strG.setSingleStep(0.1)
        self.strG.setObjectName("strG")
        self.formLayout_6.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.strG)
        self.label_37 = QtWidgets.QLabel(self.tab_3)
        self.label_37.setText("SpiG")
        self.label_37.setObjectName("label_37")
        self.formLayout_6.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_37)
        self.spiG = QtWidgets.QDoubleSpinBox(self.tab_3)
        self.spiG.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.spiG.setPrefix("")
        self.spiG.setSuffix("")
        self.spiG.setDecimals(1)
        self.spiG.setMinimum(1.0)
        self.spiG.setSingleStep(0.1)
        self.spiG.setObjectName("spiG")
        self.formLayout_6.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.spiG)
        self.label_44 = QtWidgets.QLabel(self.tab_3)
        self.label_44.setText("MaxLustG")
        self.label_44.setObjectName("label_44")
        self.formLayout_6.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_44)
        self.mLustG = QtWidgets.QSpinBox(self.tab_3)
        self.mLustG.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.mLustG.setSuffix("")
        self.mLustG.setPrefix("")
        self.mLustG.setMaximum(500)
        self.mLustG.setSingleStep(5)
        self.mLustG.setObjectName("mLustG")
        self.formLayout_6.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.mLustG)
        self.label_42 = QtWidgets.QLabel(self.tab_3)
        self.label_42.setText("MaxHPG")
        self.label_42.setObjectName("label_42")
        self.formLayout_6.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_42)
        self.mHPG = QtWidgets.QSpinBox(self.tab_3)
        self.mHPG.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.mHPG.setSuffix("")
        self.mHPG.setPrefix("")
        self.mHPG.setMaximum(500)
        self.mHPG.setSingleStep(5)
        self.mHPG.setObjectName("mHPG")
        self.formLayout_6.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.mHPG)
        self.label_46 = QtWidgets.QLabel(self.tab_3)
        self.label_46.setText("MaxSPG")
        self.label_46.setObjectName("label_46")
        self.formLayout_6.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_46)
        self.mSPG = QtWidgets.QSpinBox(self.tab_3)
        self.mSPG.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.mSPG.setSuffix("")
        self.mSPG.setPrefix("")
        self.mSPG.setMaximum(500)
        self.mSPG.setSingleStep(5)
        self.mSPG.setObjectName("mSPG")
        self.formLayout_6.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.mSPG)
        self.verticalLayout_6.addLayout(self.formLayout_6)
        self.tabWidget_2.addTab(self.tab_3, "Ranks")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.formLayout_7 = QtWidgets.QFormLayout()
        self.formLayout_7.setObjectName("formLayout_7")
        self.label_27 = QtWidgets.QLabel(self.tab_4)
        self.label_27.setText("Dex")
        self.label_27.setObjectName("label_27")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_27)
        self.label_32 = QtWidgets.QLabel(self.tab_4)
        self.label_32.setText("Int")
        self.label_32.setObjectName("label_32")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_32)
        self.label_28 = QtWidgets.QLabel(self.tab_4)
        self.label_28.setText("Lib")
        self.label_28.setObjectName("label_28")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_28)
        self.label_30 = QtWidgets.QLabel(self.tab_4)
        self.label_30.setText("Sta")
        self.label_30.setObjectName("label_30")
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_30)
        self.label_31 = QtWidgets.QLabel(self.tab_4)
        self.label_31.setText("Str")
        self.label_31.setObjectName("label_31")
        self.formLayout_7.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_31)
        self.label_29 = QtWidgets.QLabel(self.tab_4)
        self.label_29.setText("Spi")
        self.label_29.setObjectName("label_29")
        self.formLayout_7.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_29)
        self.label_43 = QtWidgets.QLabel(self.tab_4)
        self.label_43.setText("MaxLust")
        self.label_43.setObjectName("label_43")
        self.formLayout_7.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_43)
        self.label_41 = QtWidgets.QLabel(self.tab_4)
        self.label_41.setText("MaxHP")
        self.label_41.setObjectName("label_41")
        self.formLayout_7.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_41)
        self.label_4 = QtWidgets.QLabel(self.tab_4)
        self.label_4.setText("MaxSP")
        self.label_4.setObjectName("label_4")
        self.formLayout_7.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.dex = QtWidgets.QSpinBox(self.tab_4)
        self.dex.setStyleSheet("")
        self.dex.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.dex.setSuffix("")
        self.dex.setPrefix("")
        self.dex.setMinimum(1)
        self.dex.setMaximum(999)
        self.dex.setObjectName("dex")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.dex)
        self.inte = QtWidgets.QSpinBox(self.tab_4)
        self.inte.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.inte.setSuffix("")
        self.inte.setPrefix("")
        self.inte.setMinimum(1)
        self.inte.setMaximum(999)
        self.inte.setObjectName("inte")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.inte)
        self.lib = QtWidgets.QSpinBox(self.tab_4)
        self.lib.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.lib.setSuffix("")
        self.lib.setPrefix("")
        self.lib.setMinimum(1)
        self.lib.setMaximum(999)
        self.lib.setObjectName("lib")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lib)
        self.sta = QtWidgets.QSpinBox(self.tab_4)
        self.sta.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.sta.setSuffix("")
        self.sta.setPrefix("")
        self.sta.setMinimum(1)
        self.sta.setMaximum(999)
        self.sta.setObjectName("sta")
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.sta)
        self.str = QtWidgets.QSpinBox(self.tab_4)
        self.str.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.str.setSuffix("")
        self.str.setPrefix("")
        self.str.setMinimum(1)
        self.str.setMaximum(999)
        self.str.setObjectName("str")
        self.formLayout_7.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.str)
        self.spi = QtWidgets.QSpinBox(self.tab_4)
        self.spi.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.spi.setSuffix("")
        self.spi.setPrefix("")
        self.spi.setMinimum(1)
        self.spi.setMaximum(999)
        self.spi.setObjectName("spi")
        self.formLayout_7.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.spi)
        self.mLust = QtWidgets.QSpinBox(self.tab_4)
        self.mLust.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.mLust.setSuffix("")
        self.mLust.setPrefix("")
        self.mLust.setMinimum(1)
        self.mLust.setMaximum(999)
        self.mLust.setObjectName("mLust")
        self.formLayout_7.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.mLust)
        self.mHP = QtWidgets.QSpinBox(self.tab_4)
        self.mHP.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.mHP.setSuffix("")
        self.mHP.setPrefix("")
        self.mHP.setMinimum(1)
        self.mHP.setMaximum(999)
        self.mHP.setObjectName("mHP")
        self.formLayout_7.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.mHP)
        self.mSP = QtWidgets.QSpinBox(self.tab_4)
        self.mSP.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.mSP.setSuffix("")
        self.mSP.setPrefix("")
        self.mSP.setMinimum(1)
        self.mSP.setMaximum(999)
        self.mSP.setObjectName("mSP")
        self.formLayout_7.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.mSP)
        self.verticalLayout_7.addLayout(self.formLayout_7)
        self.tabWidget_2.addTab(self.tab_4, "Base")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab_5)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.formLayout_8 = QtWidgets.QFormLayout()
        self.formLayout_8.setObjectName("formLayout_8")
        self.label_19 = QtWidgets.QLabel(self.tab_5)
        self.label_19.setText("Alchemy")
        self.label_19.setObjectName("label_19")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.al = QtWidgets.QSpinBox(self.tab_5)
        self.al.setEnabled(False)
        self.al.setSuffix("")
        self.al.setPrefix("")
        self.al.setObjectName("al")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.al)
        self.label_12 = QtWidgets.QLabel(self.tab_5)
        self.label_12.setText("Femininity")
        self.label_12.setObjectName("label_12")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.fem = QtWidgets.QDoubleSpinBox(self.tab_5)
        self.fem.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.fem.setPrefix("")
        self.fem.setSuffix("")
        self.fem.setDecimals(1)
        self.fem.setMinimum(-100.0)
        self.fem.setSingleStep(0.1)
        self.fem.setObjectName("fem")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.fem)
        self.label_8 = QtWidgets.QLabel(self.tab_5)
        self.label_8.setText("Mass")
        self.label_8.setObjectName("label_8")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.mass = QtWidgets.QDoubleSpinBox(self.tab_5)
        self.mass.setEnabled(False)
        self.mass.setPrefix("")
        self.mass.setSuffix("")
        self.mass.setObjectName("mass")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.mass)
        self.label_11 = QtWidgets.QLabel(self.tab_5)
        self.label_11.setText("Muscle")
        self.label_11.setObjectName("label_11")
        self.formLayout_8.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.mTone = QtWidgets.QDoubleSpinBox(self.tab_5)
        self.mTone.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.mTone.setPrefix("")
        self.mTone.setSuffix("")
        self.mTone.setDecimals(1)
        self.mTone.setMinimum(-100.0)
        self.mTone.setSingleStep(0.1)
        self.mTone.setObjectName("mTone")
        self.formLayout_8.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.mTone)
        self.label_16 = QtWidgets.QLabel(self.tab_5)
        self.label_16.setText("Slut")
        self.label_16.setObjectName("label_16")
        self.formLayout_8.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.slut = QtWidgets.QSpinBox(self.tab_5)
        self.slut.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.slut.setSuffix("")
        self.slut.setPrefix("")
        self.slut.setMinimum(-100)
        self.slut.setMaximum(100)
        self.slut.setSingleStep(5)
        self.slut.setObjectName("slut")
        self.formLayout_8.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.slut)
        self.label_15 = QtWidgets.QLabel(self.tab_5)
        self.label_15.setText("Sub-Dom")
        self.label_15.setObjectName("label_15")
        self.formLayout_8.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.subDom = QtWidgets.QSpinBox(self.tab_5)
        self.subDom.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.subDom.setSuffix("")
        self.subDom.setPrefix("")
        self.subDom.setMinimum(-100)
        self.subDom.setMaximum(100)
        self.subDom.setSingleStep(5)
        self.subDom.setObjectName("subDom")
        self.formLayout_8.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.subDom)
        self.label_10 = QtWidgets.QLabel(self.tab_5)
        self.label_10.setText("Weight")
        self.label_10.setObjectName("label_10")
        self.formLayout_8.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.weight = QtWidgets.QDoubleSpinBox(self.tab_5)
        self.weight.setEnabled(False)
        self.weight.setPrefix("")
        self.weight.setSuffix("")
        self.weight.setObjectName("weight")
        self.formLayout_8.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.weight)
        self.verticalLayout_8.addLayout(self.formLayout_8)
        self.tabWidget_2.addTab(self.tab_5, "Other")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tab_6)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.formLayout_9 = QtWidgets.QFormLayout()
        self.formLayout_9.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.formLayout_9.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout_9.setObjectName("formLayout_9")
        self.label_21 = QtWidgets.QLabel(self.tab_6)
        self.label_21.setText("HP")
        self.label_21.setObjectName("label_21")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.HP = QtWidgets.QSpinBox(self.tab_6)
        self.HP.setSuffix("")
        self.HP.setPrefix("")
        self.HP.setMaximum(10000)
        self.HP.setObjectName("HP")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.HP)
        self.label_17 = QtWidgets.QLabel(self.tab_6)
        self.label_17.setText("Level")
        self.label_17.setObjectName("label_17")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.lvl = QtWidgets.QSpinBox(self.tab_6)
        self.lvl.setEnabled(True)
        self.lvl.setSuffix("")
        self.lvl.setPrefix("")
        self.lvl.setObjectName("lvl")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lvl)
        self.label_23 = QtWidgets.QLabel(self.tab_6)
        self.label_23.setText("Lust")
        self.label_23.setObjectName("label_23")
        self.formLayout_9.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.lust = QtWidgets.QDoubleSpinBox(self.tab_6)
        self.lust.setPrefix("")
        self.lust.setSuffix("")
        self.lust.setDecimals(1)
        self.lust.setMaximum(10000.0)
        self.lust.setObjectName("lust")
        self.formLayout_9.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lust)
        self.label_18 = QtWidgets.QLabel(self.tab_6)
        self.label_18.setText("Sex-Lvl")
        self.label_18.setObjectName("label_18")
        self.formLayout_9.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.slvl = QtWidgets.QSpinBox(self.tab_6)
        self.slvl.setEnabled(True)
        self.slvl.setSuffix("")
        self.slvl.setPrefix("")
        self.slvl.setObjectName("slvl")
        self.formLayout_9.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.slvl)
        self.label_48 = QtWidgets.QLabel(self.tab_6)
        self.label_48.setText("SeXP")
        self.label_48.setObjectName("label_48")
        self.formLayout_9.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_48)
        self.SXP = QtWidgets.QSpinBox(self.tab_6)
        self.SXP.setEnabled(True)
        self.SXP.setSuffix("")
        self.SXP.setPrefix("")
        self.SXP.setMaximum(100000)
        self.SXP.setObjectName("SXP")
        self.formLayout_9.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.SXP)
        self.label_50 = QtWidgets.QLabel(self.tab_6)
        self.label_50.setText("SeXP2Lvl")
        self.label_50.setObjectName("label_50")
        self.formLayout_9.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_50)
        self.sxp2lvl = QtWidgets.QSpinBox(self.tab_6)
        self.sxp2lvl.setEnabled(True)
        self.sxp2lvl.setSuffix("")
        self.sxp2lvl.setPrefix("")
        self.sxp2lvl.setMaximum(100000)
        self.sxp2lvl.setObjectName("sxp2lvl")
        self.formLayout_9.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.sxp2lvl)
        self.label_22 = QtWidgets.QLabel(self.tab_6)
        self.label_22.setText("SP")
        self.label_22.setObjectName("label_22")
        self.formLayout_9.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.SP = QtWidgets.QSpinBox(self.tab_6)
        self.SP.setSuffix("")
        self.SP.setPrefix("")
        self.SP.setMaximum(10000)
        self.SP.setObjectName("SP")
        self.formLayout_9.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.SP)
        self.label_47 = QtWidgets.QLabel(self.tab_6)
        self.label_47.setText("XP")
        self.label_47.setObjectName("label_47")
        self.formLayout_9.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_47)
        self.XP = QtWidgets.QSpinBox(self.tab_6)
        self.XP.setEnabled(True)
        self.XP.setSuffix("")
        self.XP.setPrefix("")
        self.XP.setMaximum(100000)
        self.XP.setObjectName("XP")
        self.formLayout_9.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.XP)
        self.label_49 = QtWidgets.QLabel(self.tab_6)
        self.label_49.setText("XP2Lvl")
        self.label_49.setObjectName("label_49")
        self.formLayout_9.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_49)
        self.xp2lvl = QtWidgets.QSpinBox(self.tab_6)
        self.xp2lvl.setEnabled(True)
        self.xp2lvl.setSuffix("")
        self.xp2lvl.setPrefix("")
        self.xp2lvl.setMaximum(100000)
        self.xp2lvl.setObjectName("xp2lvl")
        self.formLayout_9.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.xp2lvl)
        self.verticalLayout_9.addLayout(self.formLayout_9)
        self.tabWidget_2.addTab(self.tab_6, "Status")
        self.verticalLayout_5.addWidget(self.tabWidget_2)
        self.frame_3 = QtWidgets.QFrame(self.player_tab)
        self.frame_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_5.addWidget(self.frame_3)
        self.label_25 = QtWidgets.QLabel(self.player_tab)
        self.label_25.setText("Jobs")
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_5.addWidget(self.label_25)
        self.job_layout = QtWidgets.QFormLayout()
        self.job_layout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.job_layout.setObjectName("job_layout")
        self.job = QtWidgets.QComboBox(self.player_tab)
        self.job.setObjectName("job")
        self.job_layout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.job)
        self.label_40 = QtWidgets.QLabel(self.player_tab)
        self.label_40.setText("XP")
        self.label_40.setObjectName("label_40")
        self.job_layout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_40)
        self.jobXP = QtWidgets.QSpinBox(self.player_tab)
        self.jobXP.setObjectName("jobXP")
        self.job_layout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.jobXP)
        self.label_45 = QtWidgets.QLabel(self.player_tab)
        self.label_45.setText("Lvl")
        self.label_45.setObjectName("label_45")
        self.job_layout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_45)
        self.jobLvl = QtWidgets.QSpinBox(self.player_tab)
        self.jobLvl.setObjectName("jobLvl")
        self.job_layout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.jobLvl)
        self.jobActive = QtWidgets.QCheckBox(self.player_tab)
        self.jobActive.setText("Active")
        self.jobActive.setObjectName("jobActive")
        self.job_layout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.jobActive)
        self.jobCurrent = QtWidgets.QPushButton(self.player_tab)
        self.jobCurrent.setText("Set as current")
        self.jobCurrent.setObjectName("jobCurrent")
        self.job_layout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.jobCurrent)
        self.verticalLayout_5.addLayout(self.job_layout)
        self.frame_5 = QtWidgets.QFrame(self.player_tab)
        self.frame_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_5.addWidget(self.frame_5)
        self.perk_layout = QtWidgets.QGridLayout()
        self.perk_layout.setObjectName("perk_layout")
        self.perkFer = QtWidgets.QCheckBox(self.player_tab)
        self.perkFer.setEnabled(True)
        self.perkFer.setText("Fertility")
        self.perkFer.setObjectName("perkFer")
        self.perk_layout.addWidget(self.perkFer, 2, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.player_tab)
        self.label_26.setText("Perks")
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.perk_layout.addWidget(self.label_26, 0, 0, 1, 2)
        self.perkVir = QtWidgets.QCheckBox(self.player_tab)
        self.perkVir.setEnabled(True)
        self.perkVir.setText("Virility")
        self.perkVir.setObjectName("perkVir")
        self.perk_layout.addWidget(self.perkVir, 2, 1, 1, 1)
        self.perkBre = QtWidgets.QCheckBox(self.player_tab)
        self.perkBre.setEnabled(True)
        self.perkBre.setText("Breeder")
        self.perkBre.setObjectName("perkBre")
        self.perk_layout.addWidget(self.perkBre, 3, 0, 1, 1)
        self.perkFlee = QtWidgets.QCheckBox(self.player_tab)
        self.perkFlee.setEnabled(True)
        self.perkFlee.setText("Fleetfoot")
        self.perkFlee.setObjectName("perkFlee")
        self.perk_layout.addWidget(self.perkFlee, 3, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.perk_layout)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.frame = QtWidgets.QFrame(self.player_tab)
        self.frame.setFrameShape(QtWidgets.QFrame.VLine)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.horizontalLayout.addWidget(self.frame)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.player_tab)
        self.label_3.setStyleSheet("")
        self.label_3.setText("\"Equipment\"")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.toolBox_2 = QtWidgets.QToolBox(self.player_tab)
        self.toolBox_2.setStyleSheet("")
        self.toolBox_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.toolBox_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.toolBox_2.setObjectName("toolBox_2")
        self.toolBox_2Page1 = QtWidgets.QWidget()
        self.toolBox_2Page1.setGeometry(QtCore.QRect(0, 0, 244, 414))
        self.toolBox_2Page1.setObjectName("toolBox_2Page1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.toolBox_2Page1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_2.setFormAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.formLayout_2.setHorizontalSpacing(1)
        self.formLayout_2.setObjectName("formLayout_2")
        self.cockSelect = QtWidgets.QComboBox(self.toolBox_2Page1)
        self.cockSelect.setCurrentText("")
        self.cockSelect.setObjectName("cockSelect")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.cockSelect)
        self.cockRem = QtWidgets.QPushButton(self.toolBox_2Page1)
        self.cockRem.setText("Remove")
        self.cockRem.setObjectName("cockRem")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.cockRem)
        self.cockAdd = QtWidgets.QPushButton(self.toolBox_2Page1)
        self.cockAdd.setText("Add new (to bottom)")
        self.cockAdd.setObjectName("cockAdd")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cockAdd)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout_2.setItem(2, QtWidgets.QFormLayout.SpanningRole, spacerItem)
        self.label_53 = QtWidgets.QLabel(self.toolBox_2Page1)
        self.label_53.setText("Length")
        self.label_53.setObjectName("label_53")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_53)
        self.cockLen = QtWidgets.QDoubleSpinBox(self.toolBox_2Page1)
        self.cockLen.setObjectName("cockLen")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.cockLen)
        self.label_54 = QtWidgets.QLabel(self.toolBox_2Page1)
        self.label_54.setText("Thickness")
        self.label_54.setObjectName("label_54")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_54)
        self.cockThk = QtWidgets.QDoubleSpinBox(self.toolBox_2Page1)
        self.cockThk.setObjectName("cockThk")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.cockThk)
        self.label_55 = QtWidgets.QLabel(self.toolBox_2Page1)
        self.label_55.setText("Knot")
        self.label_55.setObjectName("label_55")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_55)
        self.cockKnot = QtWidgets.QSpinBox(self.toolBox_2Page1)
        self.cockKnot.setObjectName("cockKnot")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.cockKnot)
        self.label_56 = QtWidgets.QLabel(self.toolBox_2Page1)
        self.label_56.setText("Race")
        self.label_56.setObjectName("label_56")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_56)
        self.cockRace = QtWidgets.QComboBox(self.toolBox_2Page1)
        self.cockRace.setObjectName("cockRace")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.cockRace)
        self.label_57 = QtWidgets.QLabel(self.toolBox_2Page1)
        self.label_57.setText("Color")
        self.label_57.setObjectName("label_57")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_57)
        self.cockColor = QtWidgets.QComboBox(self.toolBox_2Page1)
        self.cockColor.setObjectName("cockColor")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.cockColor)
        self.label_58 = QtWidgets.QLabel(self.toolBox_2Page1)
        self.label_58.setText("Type")
        self.label_58.setObjectName("label_58")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_58)
        self.cockType = QtWidgets.QComboBox(self.toolBox_2Page1)
        self.cockType.setEnabled(False)
        self.cockType.setObjectName("cockType")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.cockType)
        self.verticalLayout_2.addLayout(self.formLayout_2)
        self.toolBox_2.addItem(self.toolBox_2Page1, "Cock(s)")
        self.toolBox_2Page2 = QtWidgets.QWidget()
        self.toolBox_2Page2.setGeometry(QtCore.QRect(0, 0, 244, 414))
        self.toolBox_2Page2.setObjectName("toolBox_2Page2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.toolBox_2Page2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_59 = QtWidgets.QLabel(self.toolBox_2Page2)
        self.label_59.setText("Count")
        self.label_59.setObjectName("label_59")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_59)
        self.ballsCount = QtWidgets.QSpinBox(self.toolBox_2Page2)
        self.ballsCount.setObjectName("ballsCount")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.ballsCount)
        self.ballsSize = QtWidgets.QDoubleSpinBox(self.toolBox_2Page2)
        self.ballsSize.setObjectName("ballsSize")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.ballsSize)
        self.ballsFer = QtWidgets.QDoubleSpinBox(self.toolBox_2Page2)
        self.ballsFer.setObjectName("ballsFer")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.ballsFer)
        self.label_60 = QtWidgets.QLabel(self.toolBox_2Page2)
        self.label_60.setText("Size")
        self.label_60.setObjectName("label_60")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_60)
        self.label_61 = QtWidgets.QLabel(self.toolBox_2Page2)
        self.label_61.setText("Fertility")
        self.label_61.setObjectName("label_61")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_61)
        self.ballsCum = QtWidgets.QDoubleSpinBox(self.toolBox_2Page2)
        self.ballsCum.setObjectName("ballsCum")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.ballsCum)
        self.ballsCumP = QtWidgets.QDoubleSpinBox(self.toolBox_2Page2)
        self.ballsCumP.setObjectName("ballsCumP")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.ballsCumP)
        self.ballsCumC = QtWidgets.QDoubleSpinBox(self.toolBox_2Page2)
        self.ballsCumC.setObjectName("ballsCumC")
        self.formLayout_4.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.ballsCumC)
        self.label_62 = QtWidgets.QLabel(self.toolBox_2Page2)
        self.label_62.setText("Cum")
        self.label_62.setObjectName("label_62")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_62)
        self.label_63 = QtWidgets.QLabel(self.toolBox_2Page2)
        self.label_63.setText("Cum Production")
        self.label_63.setObjectName("label_63")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_63)
        self.label_64 = QtWidgets.QLabel(self.toolBox_2Page2)
        self.label_64.setText("Cum Capacity")
        self.label_64.setObjectName("label_64")
        self.formLayout_4.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_64)
        self.ballsRace = QtWidgets.QComboBox(self.toolBox_2Page2)
        self.ballsRace.setObjectName("ballsRace")
        self.formLayout_4.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.ballsRace)
        self.ballsCol = QtWidgets.QComboBox(self.toolBox_2Page2)
        self.ballsCol.setObjectName("ballsCol")
        self.formLayout_4.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.ballsCol)
        self.label_65 = QtWidgets.QLabel(self.toolBox_2Page2)
        self.label_65.setText("Race")
        self.label_65.setObjectName("label_65")
        self.formLayout_4.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_65)
        self.label_66 = QtWidgets.QLabel(self.toolBox_2Page2)
        self.label_66.setText("Color")
        self.label_66.setObjectName("label_66")
        self.formLayout_4.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_66)
        self.verticalLayout_3.addLayout(self.formLayout_4)
        self.toolBox_2.addItem(self.toolBox_2Page2, "Balls")
        self.toolBox_2Page3 = QtWidgets.QWidget()
        self.toolBox_2Page3.setGeometry(QtCore.QRect(0, 0, 244, 414))
        self.toolBox_2Page3.setObjectName("toolBox_2Page3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.toolBox_2Page3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setObjectName("formLayout_5")
        self.verticalLayout_4.addLayout(self.formLayout_5)
        self.toolBox_2.addItem(self.toolBox_2Page3, "Vagina(s)")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 244, 414))
        self.page.setObjectName("page")
        self.toolBox_2.addItem(self.page, "Ass")
        self.verticalLayout.addWidget(self.toolBox_2)
        self.label_67 = QtWidgets.QLabel(self.player_tab)
        self.label_67.setText("Genitalia cover")
        self.label_67.setObjectName("label_67")
        self.verticalLayout.addWidget(self.label_67)
        self.genCover = QtWidgets.QComboBox(self.player_tab)
        self.genCover.setObjectName("genCover")
        self.verticalLayout.addWidget(self.genCover)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.frame_2 = QtWidgets.QFrame(self.player_tab)
        self.frame_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout.addWidget(self.frame_2)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_33 = QtWidgets.QLabel(self.player_tab)
        self.label_33.setMinimumSize(QtCore.QSize(230, 0))
        self.label_33.setStyleSheet("")
        self.label_33.setText("Body")
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_33)
        self.horizontalLayout.addLayout(self.formLayout_3)
        self.tabWidget.addTab(self.player_tab, "Player")
        self.Inv_tab = QtWidgets.QWidget()
        self.Inv_tab.setObjectName("Inv_tab")
        self.layoutWidget = QtWidgets.QWidget(self.Inv_tab)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 232, 220))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(-1, 5, -1, -1)
        self.formLayout.setHorizontalSpacing(1)
        self.formLayout.setVerticalSpacing(6)
        self.formLayout.setObjectName("formLayout")
        self.label_13 = QtWidgets.QLabel(self.layoutWidget)
        self.label_13.setText("Equipment")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_13)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        self.label_9.setText("Weapon")
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.weapon = QtWidgets.QComboBox(self.layoutWidget)
        self.weapon.setEnabled(True)
        self.weapon.setStyleSheet("")
        self.weapon.setObjectName("weapon")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.weapon)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget)
        self.label_14.setStyleSheet("")
        self.label_14.setText("Toy")
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.toy = QtWidgets.QComboBox(self.layoutWidget)
        self.toy.setEnabled(True)
        self.toy.setObjectName("toy")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.toy)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setToolTip("")
        self.label.setText("Acc1")
        self.label.setObjectName("label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label)
        self.acc1 = QtWidgets.QComboBox(self.layoutWidget)
        self.acc1.setToolTipDuration(-1)
        self.acc1.setStatusTip("")
        self.acc1.setWhatsThis("")
        self.acc1.setAccessibleName("")
        self.acc1.setAccessibleDescription("")
        self.acc1.setCurrentText("")
        self.acc1.setMinimumContentsLength(4)
        self.acc1.setObjectName("acc1")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.acc1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setText("Acc2")
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.acc2 = QtWidgets.QComboBox(self.layoutWidget)
        self.acc2.setCurrentText("")
        self.acc2.setObjectName("acc2")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.acc2)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setText("Top")
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.armTop = QtWidgets.QComboBox(self.layoutWidget)
        self.armTop.setCurrentText("")
        self.armTop.setObjectName("armTop")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.armTop)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setText("Bottom")
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.armBot = QtWidgets.QComboBox(self.layoutWidget)
        self.armBot.setCurrentText("")
        self.armBot.setObjectName("armBot")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.armBot)
        self.label_52 = QtWidgets.QLabel(self.Inv_tab)
        self.label_52.setGeometry(QtCore.QRect(20, 10, 121, 21))
        self.label_52.setStyleSheet("font: 12pt \"Segoe UI Semilight\";\n"
"color: rgb(255, 0, 0);")
        self.label_52.setText("Temporary layout")
        self.label_52.setObjectName("label_52")
        self.tabWidget.addTab(self.Inv_tab, "Inventory")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_68 = QtWidgets.QLabel(self.tab)
        self.label_68.setGeometry(QtCore.QRect(10, 20, 151, 21))
        self.label_68.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: rgb(255, 0, 0);")
        self.label_68.setText("Future build")
        self.label_68.setObjectName("label_68")
        self.tabWidget.addTab(self.tab, "Party")
        self.tree_tab = QtWidgets.QWidget()
        self.tree_tab.setEnabled(True)
        self.tree_tab.setObjectName("tree_tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tree_tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tree_widget = QtWidgets.QTreeWidget(self.tree_tab)
        self.tree_widget.setObjectName("tree_widget")
        self.tree_widget.headerItem().setText(0, "1")
        self.gridLayout_2.addWidget(self.tree_widget, 0, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.tree_tab)
        self.label_24.setGeometry(QtCore.QRect(120, 190, 561, 71))
        self.label_24.setStyleSheet("font: 48pt \"Segoe UI\";")
        self.label_24.setText("TODO: This.")
        self.label_24.setObjectName("label_24")
        self.tree_widget.raise_()
        self.label_24.raise_()
        self.tabWidget.addTab(self.tree_tab, "Raw")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setTitle("File")
        self.menuFile.setObjectName("menuFile")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setTitle("About")
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setText("Open")
        self.actionOpen.setToolTip("Open file")
        self.actionOpen.setStatusTip("Open file")
        self.actionOpen.setShortcut("Ctrl+O")
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setText("Save as...")
        self.actionSave.setToolTip("Save file as...")
        self.actionSave.setStatusTip("Save file as...")
        self.actionSave.setWhatsThis("")
        self.actionSave.setShortcut("Ctrl+S")
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setText("Exit")
        self.actionExit.setToolTip("Exit apllication")
        self.actionExit.setStatusTip("Quit application")
        self.actionExit.setShortcut("Esc")
        self.actionExit.setObjectName("actionExit")
        self.actionSource = QtWidgets.QAction(MainWindow)
        self.actionSource.setText("Source")
        self.actionSource.setObjectName("actionSource")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionExit)
        self.menuAbout.addAction(self.actionSource)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        self.toolBox_2.layout().setSpacing(3)
        self.acc1.setCurrentIndex(-1)
        self.acc2.setCurrentIndex(-1)
        self.actionExit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.tree_widget.setSortingEnabled(True)

